name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: shogo82148/actions-setup-perl@v1
      
      - name: install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      - name: init a packwiz 
        run: |
          cd .minecraft
          packwiz init --author asguho --name AsguhoClient --modloader fabric --fabric-latest -l --version 1.0.0
        
      - name: downloading mods 
        run:  |
          chmod u+x modinstaller.pl
          cd .minecraft
          ../modinstaller.pl
        
      - name: export a .mrpack 
        run: |
          cd .minecraft
          packwiz mr export

      - name: export a .zid 
        run: |
          cd .minecraft
          packwiz cf export

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: .minecraft/AsguhoClient-1.0.0.zip


      - name: getting info from previous release
        id: previousrelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Asguho
          repo: AsguhoClient

      - name: printing previous release info
        runs: |
          echo ${{ steps.previousrelease.outputs.release }}
          echo ${{ steps.previousrelease.outputs.id }}

      - name: getting info for publishing   
        id: gameversions
        run: |
          chmod u+x versions.pl
          cd .minecraft
          ../versions.pl zz
        
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: .minecraft/AsguhoClient-1.0.0.mrpack        
        
          #modrinth-id: AANobbMI
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          #curseforge-id: 394468
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUBAPI_TOKEN }}
          github-tag: ${{ steps.gameversions.outputs.zz }}
