# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true

      # Runs a single command using the runners shell
      - name: install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      # Runs a single command using the runners shell
      - name: init a packwiz 
        run: packwiz init --author asguho --name AsguhoClient --modloader fabric --fabric-latest -l --version 1.0.0
        
      - name: download mods 
        run: packwiz mr install sodium
        
      - name: export a .mrpack 
        run: packwiz mr export
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: AsguhoClient-1.0.0.mrpack
          
      - uses: shogo82148/actions-setup-perl@v1
            
      - id: gameversions
        run: |
          chmod u+x versions.pl
          ./versions.pl
          #echo "::set-output name=qq::1.4.5"
          #echo "::set-output name=yy::1.4.5"
        
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          # You don't need this section if you don't want to publish
          # your assets to Modrinth
          #modrinth-id: AANobbMI
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # You don't need this section if you don't want to publish
          # your assets to CurseForge
          #curseforge-id: 394468
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # You don't need this section if you don't want to publish
          # your assets to GitHub
          files-primary: AsguhoClient-1.0.0.mrpack
          github-token: ${{ secrets.GITHUBAPI_TOKEN }}
          github-tag: ${{ steps.gameversions.outputs.zz }}
          name: ${{ steps.gameversions.outputs.bb }}
        
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
        #run: |
          #echo Add other actions to build1,
          #echo test, and deploy your project.
