name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: shogo82148/actions-setup-perl@v1
      
      - name: install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      - name: init a packwiz 
        run: packwiz init --author asguho --name AsguhoClient --modloader fabric --fabric-latest -l --version 1.0.0
        
      - name: downloading mods 
        run:  |
          chmod u+x modinstaller.pl
          ./modinstaller.pl
        
      - name: export a .mrpack 
        run: packwiz mr export
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: AsguhoClient-1.0.0.mrpack
      - name: getting info for publishing   
        id: gameversions
        run: |
          chmod u+x versions.pl
          ./versions.pl zz
        
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: AsguhoClient-1.0.0.mrpack        
        
          #modrinth-id: AANobbMI
          #modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          #curseforge-id: 394468
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          github-token: ${{ secrets.GITHUBAPI_TOKEN }}
          github-tag: ${{ steps.gameversions.outputs.zz }}
